INSERT INTO USERS(PASSWORD, USERNAME) VALUES('1234', 'alexis');

INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 1', 100);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 2', 200);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 3', 300);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 4', 400);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 5', 500);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 6', 600);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 7', 700);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 8', 800);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 9', 900);
INSERT INTO PRODUCTS(NAME, PRICE) VALUES('Prodcut 10', 1000);

INSERT INTO ORDERS(REG_DATE, TOTAL, FK_USER) VALUES(NOW(), 1500, 1);
INSERT INTO ORDER_LINES(FK_ORDER, FK_PRODUCT, PRICE, QUANTITY, TOTAL) VALUES (1,1,100,1,100);
INSERT INTO ORDER_LINES(FK_ORDER, FK_PRODUCT, PRICE, QUANTITY, TOTAL) VALUES (1,2,200,1,200);
INSERT INTO ORDER_LINES(FK_ORDER, FK_PRODUCT, PRICE, QUANTITY, TOTAL) VALUES (1,3,300,1,300);
INSERT INTO ORDER_LINES(FK_ORDER, FK_PRODUCT, PRICE, QUANTITY, TOTAL) VALUES (1,4,400,1,400);
INSERT INTO ORDER_LINES(FK_ORDER, FK_PRODUCT, PRICE, QUANTITY, TOTAL) VALUES (1,5,500,1,500);